### ISSUE TITLE
Curious about the uncertainty estimation

### ISSUE THREAD

**Issue by jiweiqi** [youyanggu/covid19_projections#6]
Curious about how the uncertainty interval is computed:

> That’s why in addition to our most likely estimate, we also provide a 95% confidence interval to reflect this uncertainty. For example, if we predict 150,760 deaths with a range of 88-294k, it means that there is roughly a 95% chance that the true deaths will be between 88-294k.

Here is my guess, hope that you can correct me.

* The uncertainties of the model parameters are first estimated. Some are based on machine learning, such as MCMC? Some are based on assignment, e.g., the uncertainty in fatality rate is assigned as 0.9 - 1.2%.

* Then the uncertainties are propagated to the projection using Monte Carlo, and report the 95% confidence interval.

**Comment by youyanggu** [comment]
We compute the confidence interval by using the simulations from the various parameter sets we compute, weighted by their in-sample errors. Monte Carlo is a good way to think of it, except rather than randomized sampling, we sample in a predetermined format and then weigh the results. As a rough example, if we have 1000 "plausible" parameter sets for a region, we can sort their projections and use that as our confidence intervals.

You can find some more details on our website: [covid19-projections.com/model-details/](https://covid19-projections.com/model-details/)
